TRADE_TYPE_ACTIVE = 'ACTIVE'
TRADE_TYPE_ACTION_REQUIRED = 'ACTION REQUIRED'
TRADE_TYPE_COMPLETED = 'COMPLETED'

TRADE_STATUS_LIST = [
    TRADE_TYPE_ACTIVE,
    TRADE_TYPE_COMPLETED,
    TRADE_TYPE_ACTION_REQUIRED
]
