# Generated by Django 3.1.5 on 2021-01-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='Trade Start Date')),
                ('expiry_date', models.DateField(verbose_name='Trade End Date')),
                ('strike', models.IntegerField(verbose_name='Strike')),
                ('r_yield', models.FloatField(verbose_name='Yield(%)')),
                ('b_ccy', models.CharField(max_length=10)),
                ('alt_ccy', models.CharField(max_length=10)),
                ('notional', models.IntegerField(verbose_name='Notional')),
            ],
        ),
    ]
