# Generated by Django 3.1.5 on 2021-01-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_trades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='r_yield',
            new_name='yield_rate',
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
