# Generated by Django 3.1.5 on 2021-01-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_trades', '0002_auto_20210105_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='strike',
            field=models.FloatField(verbose_name='Strike'),
        ),
    ]
